### ISSUE TITLE
setCallbackFunction runs always as Head deployment

### ISSUE THREAD

**Issue by etatus** [googleworkspace/apps-script-oauth2#263]
I set the function "authCallback" in setCallbackFunction when creating an OAuth2 connection (OAuth2.createService) and everything works fine. But when I saw the logs I realised the function runs always as Head deployment instead the deployment version that should be (Version 27 in this case). Why is that?

![image](https://user-images.githubusercontent.com/7522061/105576100-c0f60100-5d70-11eb-80b4-f615dbc5df2a.png)

**Comment by erickoledadevrel** [comment]
This behavior was also reported in [issue #208](https://github.com/googleworkspace/apps-script-oauth2/issues/208#issuecomment-764718153), and it's unclear if it's related to the "Library with identifier OAuth2 is missing" error they are seeing. Much like that issue, I believe this problem is not related to the code in this library, but rather how Apps Script itself generates state tokens and handles the `/usercallback` endpoint.

This library uses the [`ScriptApp.newStateToken()`](https://developers.google.com/apps-script/reference/script/script-app#newstatetoken) method, which doesn't provide any options for specifying the deployment version. The [`/usercallback` URL constructed](https://github.com/googleworkspace/apps-script-oauth2/blob/master/src/OAuth2.js#L54) by the library used the script ID, but the deployment ID isn't valid in that URL nor would it be feasible since you often need to register stable URLs in OAuth2 developer consoles.

I suggest filing a new bug via the process listed on the [Apps Script support page](https://developers.google.com/apps-script/support#bugs). I think the correct behavior is for Apps Script to internally capture the deployment ID in the state token and then load that version of the code in the `/usercallback` endpoint.
